import turtle
from tkinter import *

root = Tk()
root.title('单线图绘制-By avebest')
root.geometry('1000x800')
canva = Canvas(root, width=1000, height=800)
canva.place(x=0,y=0)

theScreen = turtle.TurtleScreen(canva)
t = turtle.RawTurtle(theScreen)
t.speed(0)
t.penup()
t.setpos(-350, -100)
t.pendown()

def north():
    t.seth(30)
    t.fd(40)
def up():
    t.seth(90)
    t.fd(40)
def west():
    t.seth(150)
    t.fd(40)
def south():
    t.seth(210)
    t.fd(40)
def down():
    t.seth(270)
    t.fd(40)
def east():
    t.seth(330)
    t.fd(40)
def undo():t.undo()
def falan():
    t.lt(90)
    t.fd(5)
    t.bk(10)
    t.penup()
    t.rt(90)
    t.fd(3)
    t.lt(90)
    t.pendown()
    t.fd(10)
    t.bk(5)
    t.rt(90)
def famen():
    t.lt(90)
    t.fd(5)
    t.rt(120)
    t.fd(20)
    t.lt(120)
    t.fd(10)
    t.lt(120)
    t.fd(20)
    t.rt(120)
    t.fd(5)
    t.penup()
    t.fd(5)
    t.rt(120)
    t.fd(20)
    t.lt(120)
    t.fd(5)
    t.rt(90)
    t.pendown()
def finish():
    falan()
    t.hideturtle()


button_west = Button(root, text='西', command=west)
button_west.place(x=663, y=580)
button_up = Button(root, text='上', command=up)
button_up.place(x=726, y=540)
button_north = Button(root, text='北', command=north)
button_north.place(x=791, y=580)
button_east = Button(root, text='东', command=east)
button_east.place(x=791, y=653)
button_down = Button(root, text='下', command=down)
button_down.place(x=726, y=693)
button_south = Button(root, text='南', command=south)
button_south.place(x=663, y=653)
button_undo = Button(root, text='撤销', command=undo)
button_undo.place(x=865, y=580)
button_falan = Button(root, text='法兰', command=falan)
button_falan.place(x=530, y=710)
button_famen = Button(root, text='阀门', command=famen)
button_famen.place(x=470, y=710)
button_finish = Button(root, text='结束', command=finish)
button_finish.place(x=865, y=623)
photo = PhotoImage(file="six.gif")
label_photo = Label(root, image=photo, borderwidth=0)
label_photo.place(x=741, y=635, anchor='center')

theScreen.mainloop()
root.mainloop()
